{
  hm.home.file.".XCompose".text = ''
    include "%L"

    <Multi_key> <space> <space> : "␣"
    <Multi_key> <Up> : "↑"
    <Multi_key> <Down> : "↓"
    <Multi_key> <Left> : "←"
    <Multi_key> <Right> : "→"
    <Multi_key> <Tab> : "⇥"
    <Multi_key> <Return> : "↵"
    <Multi_key> <s> <h> : "¯\\_(ツ)_/¯"
    <Multi_key> <s> <2> <h> : "┐('~'; )┌"
    <Multi_key> <l> <e> : "( ͡° ͜ʖ ͡°)"
    <Multi_key> <m> <e> <h> : "ಠ_ಠ"
    <Multi_key> <t> <f> : "(╯°□°）╯︵ ┻━┻"
    <Multi_key> <q> <t> : "(◕‿◕)"
    <Multi_key> <i> <n> <f> : "∞"
    <Multi_key> <f> <l> : "❧"
    <Multi_key> <o> <k> : "✓"
    <Multi_key> <n> <o> <k> : "✗"
    <Multi_key> <r> <r> : "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    <Multi_key> <asciitilde> <equal> : "≅"
    <Multi_key> <l> <a> <n> <d> : "∧"
    <Multi_key> <l> <o> <r> : "∨"
    <Multi_key> <i> <f> <f> : "⇔"
    <Multi_key> <t> <o> <p> : "⊤"
    <Multi_key> <b> <o> <t> : "⊥"
    <Multi_key> <underscore> <bar> <underscore> : "⊥"
    <Multi_key> <e> <x> : "∃"
    <Multi_key> <slash> <e> <x> : "∄"
    <Multi_key> <a> <l> <l> : "∀"
    <Multi_key> <bar> <minus> : "⊢"
    <Multi_key> <bar> <equal> : "⊨"
    <Multi_key> <m> <e> <m> : "∈"
    <Multi_key> <i> <n> <c> : "⊂"
    <Multi_key> <c> <u> <p> : "∪"
    <Multi_key> <c> <a> <p> : "∩"
    <Multi_key> <n> <m> <e> <m> : "∉"
    <Multi_key> <slash> <i> <n> <c> : "⊄"
    <Multi_key> <a> <l> <e> <p> <h> : "ℵ"
    <Multi_key> <B> <A> : "𝔸"
    <Multi_key> <B> <B> : "𝔹"
    <Multi_key> <B> <C> : "ℂ"
    <Multi_key> <B> <D> : "𝔻"
    <Multi_key> <B> <E> : "𝔼"
    <Multi_key> <B> <F> : "𝔽"
    <Multi_key> <B> <G> : "𝔾"
    <Multi_key> <B> <H> : "ℍ"
    <Multi_key> <B> <I> : "𝕀"
    <Multi_key> <B> <J> : "𝕁"
    <Multi_key> <B> <K> : "𝕂"
    <Multi_key> <B> <L> : "𝕃"
    <Multi_key> <B> <M> : "𝕄"
    <Multi_key> <B> <N> : "ℕ"
    <Multi_key> <B> <O> : "𝕆"
    <Multi_key> <B> <P> : "ℙ"
    <Multi_key> <B> <Q> : "ℚ"
    <Multi_key> <B> <R> : "ℝ"
    <Multi_key> <B> <S> : "𝕊"
    <Multi_key> <B> <T> : "𝕋"
    <Multi_key> <B> <U> : "𝕌"
    <Multi_key> <B> <V> : "𝕍"
    <Multi_key> <B> <W> : "𝕎"
    <Multi_key> <B> <X> : "𝕏"
    <Multi_key> <B> <Y> : "𝕐"
    <Multi_key> <B> <Z> : "ℤ"
    <Multi_key> <B> <1> : "𝟙"
    <Multi_key> <B> <0> : "𝟘"
    <Multi_key> <f> <l> <l> : "⌊"
    <Multi_key> <f> <l> <r> : "⌋"
    <Multi_key> <c> <e> <l> : "⌈"
    <Multi_key> <c> <e> <r> : "⌉"
    <Multi_key> <o> <asterisk> : "⊗"
    <Multi_key> <o> <plus> : "⊕"
    <Multi_key> <ampersand> <ampersand> : "⅋"
    <Multi_key> <p> <a> <r> : "⅋"
    <Multi_key> <minus> <o> : "⊸"
    <Multi_key> <l> <o> <l> : "⊸"
  '';
}
