{
  hm.home.file.".XCompose" = {
    text = ''
      include "%L"

      <Multi_key> <less> <bar> : "◂"
      <Multi_key> <bar> <greater> : "▸"
      <Multi_key> <b> <o> <x> : "□"
      <Multi_key> <bar> <Right> : "↦"
      <Multi_key> <q> <e> <d> : "∎"
      <Multi_key> <o> <o> : "∘"
      <Multi_key> <asterisk> <asterisk> : "⋆"
      <Multi_key> <asterisk> <period> : "∙"
      <Multi_key> <asterisk> <comma> : "·"
      <Multi_key> <asterisk> <o> : "∘"
      <Multi_key> <less> <asterisk> <greater> : "⊛"
      <Multi_key> <x> <bar> : "⋊"
      <Multi_key> <w> <r> : "≀"
      <Multi_key> <equal> <equal> : "≡"
      <Multi_key> <equal> <3> : "≡"
      <Multi_key> <equal> <slash> <equal> : "≢"
      <Multi_key> <equal> <slash> <3> : "≢"
      <Multi_key> <equal> <4> : "≣"
      <Multi_key> <asciitilde> <equal> : "≃"
      <Multi_key> <equal> <asciitilde> : "≅"
      <Multi_key> <asciitilde> <asciitilde> : "≈"
      <Multi_key> <question> <equal> : "≟"
      <Multi_key> <period> <equal> : "≐"
      <Multi_key> <equal> <period> : "≐"
      <Multi_key> <less> <parenleft> : "⟨"
      <Multi_key> <greater> <parenright> : "⟩"
      <Multi_key> <parenleft> <less> : "⟨"
      <Multi_key> <parenright> <greater> : "⟩"
      <Multi_key> <parenleft> <bar> : "⦇"
      <Multi_key> <bar> <parenright> : "⦈"
      <Multi_key> <bracketleft> <bar> : "⟦"
      <Multi_key> <bar> <bracketright> : "⟧"
      <Multi_key> <braceleft> <bar> : "⦃"
      <Multi_key> <bar> <braceright> : "⦄"
      <Multi_key> <underscore> <bracketleft> : "⌞"
      <Multi_key> <bracketleft> <underscore> : "⌞"
      <Multi_key> <underscore> <bracketright> : "⌟"
      <Multi_key> <bracketright> <underscore> : "⌟"
      <Multi_key> <parenleft> <parenright> : "≬"
      <Multi_key> <less> <less> : "≪"
      <Multi_key> <greater> <greater> : "≫"
      <Multi_key> <bar> <bar> : "∥"
      <Multi_key> <slash> <backslash> : "∧"
      <Multi_key> <l> <a> <n> <d> : "∧"
      <Multi_key> <l> <o> <r> : "∨"
      <Multi_key> <i> <f> <f> : "⇔"
      <Multi_key> <t> <o> <p> : "⊤"
      <Multi_key> <b> <o> <t> : "⊥"
      <Multi_key> <underscore> <bar> <underscore> : "⊥"
      <Multi_key> <e> <x> : "∃"
      <Multi_key> <slash> <e> <x> : "∄"
      <Multi_key> <a> <l> <l> : "∀"
      <Multi_key> <bar> <minus> : "⊢"
      <Multi_key> <minus> <bar> : "⊣"
      <Multi_key> <bar> <equal> : "⊨"
      <Multi_key> <m> <e> <m> : "∈"
      <Multi_key> <n> <m> <e> <m> : "∉"
      <Multi_key> <i> <n> <c> : "⊂"
      <Multi_key> <n> <i> <n> <c> : "⊄"
      <Multi_key> <slash> <i> <n> <c> : "⊄"
      <Multi_key> <equal> <i> <n> <c> : "⊆"
      <Multi_key> <c> <u> <p> : "∪"
      <Multi_key> <c> <a> <p> : "∩"
      <Multi_key> <s> <q> <c> <u> <p> : "⊔"
      <Multi_key> <s> <q> <c> <a> <p> : "⊓"
      <Multi_key> <U> <plus> : "⊎"
      <Multi_key> <slash> <0> : "∅"
      <Multi_key> <i> <n> <f> : "∞"
      <Multi_key> <a> <l> <e> <p> <h> : "ℵ"
      <Multi_key> <a> <l> <e> <f> : "ℵ"
      <Multi_key> <o> <asterisk> : "⊗"
      <Multi_key> <o> <plus> : "⊕"
      <Multi_key> <o> <period> : "⊙"
      <Multi_key> <ampersand> <ampersand> : "⅋"
      <Multi_key> <p> <a> <r> : "⅋"
      <Multi_key> <minus> <o> : "⊸"
      <Multi_key> <s> <q> : "√"
      <Multi_key> <3> <s> <q> : "∛"
      <Multi_key> <4> <s> <q> : "∜"
      <Multi_key> <i> <n> <t> : "∫"
      <Multi_key> <1> <slash> <4> : "¼"
      <Multi_key> <1> <slash> <2> : "½"
      <Multi_key> <3> <slash> <4> : "¾"
      <Multi_key> <1> <slash> <3> : "⅓"
      <Multi_key> <2> <slash> <3> : "⅔"
      <Multi_key> <1> <slash> <5> : "⅕"
      <Multi_key> <2> <slash> <5> : "⅖"
      <Multi_key> <3> <slash> <5> : "⅗"
      <Multi_key> <4> <slash> <5> : "⅘"
      <Multi_key> <1> <slash> <6> : "⅙"
      <Multi_key> <5> <slash> <6> : "⅚"
      <Multi_key> <1> <slash> <8> : "⅛"
      <Multi_key> <3> <slash> <8> : "⅜"
      <Multi_key> <5> <slash> <8> : "⅝"
      <Multi_key> <7> <slash> <8> : "⅞"
      <Multi_key> <underscore> <a> : "ₐ"
      <Multi_key> <underscore> <e> : "ₑ"
      <Multi_key> <underscore> <i> : "ᵢ"
      <Multi_key> <underscore> <j> : "ⱼ"
      <Multi_key> <underscore> <h> : "ₕ"
      <Multi_key> <underscore> <k> : "ₖ"
      <Multi_key> <underscore> <l> : "ₗ"
      <Multi_key> <underscore> <m> : "ₘ"
      <Multi_key> <underscore> <n> : "ₙ"
      <Multi_key> <underscore> <o> : "ₒ"
      <Multi_key> <underscore> <p> : "ₚ"
      <Multi_key> <underscore> <s> : "ₛ"
      <Multi_key> <underscore> <t> : "ₜ"
      <Multi_key> <underscore> <u> : "ᵤ"
      <Multi_key> <underscore> <x> : "ₓ"
      <dead_circumflex> <b> : "ᵇ"
      <dead_circumflex> <c> : "ᶜ"
      <dead_circumflex> <d> : "ᵈ"
      <Multi_key> <asciicircum> <e> : "ᵉ"
      <dead_circumflex> <f> : "ᶠ"
      <dead_circumflex> <h> : "ʰ"
      <Multi_key> <asciicircum> <j> : "ʲ"
      <dead_circumflex> <l> : "ˡ"
      <dead_circumflex> <m> : "ᵐ"
      <dead_circumflex> <n> : "ⁿ"
      <dead_circumflex> <r> : "ʳ"
      <Multi_key> <asciicircum> <s> : "ˢ"
      <Multi_key> <asciicircum> <w> : "ʷ"
      <dead_circumflex> <x> : "ˣ"
      <Multi_key> <asciicircum> <y> : "ʸ"
      <dead_circumflex> <apostrophe> : "′"
      <Multi_key> <C> <A> : "𝒜"
      <Multi_key> <C> <B> : "ℬ"
      <Multi_key> <C> <C> : "𝒞"
      <Multi_key> <C> <D> : "𝒟"
      <Multi_key> <C> <E> : "ℰ"
      <Multi_key> <C> <F> : "ℱ"
      <Multi_key> <C> <G> : "𝒢"
      <Multi_key> <C> <H> : "ℋ"
      <Multi_key> <C> <I> : "𝒥"
      <Multi_key> <C> <J> : "ℐ"
      <Multi_key> <C> <K> : "𝒦"
      <Multi_key> <C> <L> : "ℒ"
      <Multi_key> <C> <M> : "ℳ"
      <Multi_key> <C> <N> : "𝒩"
      <Multi_key> <C> <O> : "𝒪"
      <Multi_key> <C> <P> : "𝒫"
      <Multi_key> <C> <Q> : "𝒬"
      <Multi_key> <C> <R> : "ℛ"
      <Multi_key> <C> <S> : "𝒮"
      <Multi_key> <C> <T> : "𝒯"
      <Multi_key> <C> <U> : "𝒰"
      <Multi_key> <C> <V> : "𝒱"
      <Multi_key> <C> <W> : "𝒲"
      <Multi_key> <C> <X> : "𝒳"
      <Multi_key> <C> <Y> : "𝒴"
      <Multi_key> <C> <Z> : "𝒵"
      <Multi_key> <B> <A> : "𝔸"
      <Multi_key> <B> <B> : "𝔹"
      <Multi_key> <B> <C> : "ℂ"
      <Multi_key> <B> <D> : "𝔻"
      <Multi_key> <B> <E> : "𝔼"
      <Multi_key> <B> <F> : "𝔽"
      <Multi_key> <B> <G> : "𝔾"
      <Multi_key> <B> <H> : "ℍ"
      <Multi_key> <B> <I> : "𝕀"
      <Multi_key> <B> <J> : "𝕁"
      <Multi_key> <B> <K> : "𝕂"
      <Multi_key> <B> <L> : "𝕃"
      <Multi_key> <B> <M> : "𝕄"
      <Multi_key> <B> <N> : "ℕ"
      <Multi_key> <B> <O> : "𝕆"
      <Multi_key> <B> <P> : "ℙ"
      <Multi_key> <B> <Q> : "ℚ"
      <Multi_key> <B> <R> : "ℝ"
      <Multi_key> <B> <S> : "𝕊"
      <Multi_key> <B> <T> : "𝕋"
      <Multi_key> <B> <U> : "𝕌"
      <Multi_key> <B> <V> : "𝕍"
      <Multi_key> <B> <W> : "𝕎"
      <Multi_key> <B> <X> : "𝕏"
      <Multi_key> <B> <Y> : "𝕐"
      <Multi_key> <B> <Z> : "ℤ"
      <Multi_key> <B> <a> : "𝕒"
      <Multi_key> <B> <b> : "𝕓"
      <Multi_key> <B> <c> : "𝕔"
      <Multi_key> <B> <d> : "𝕕"
      <Multi_key> <B> <e> : "𝕖"
      <Multi_key> <B> <f> : "𝕗"
      <Multi_key> <B> <g> : "𝕘"
      <Multi_key> <B> <h> : "𝕙"
      <Multi_key> <B> <i> : "𝕚"
      <Multi_key> <B> <j> : "𝕛"
      <Multi_key> <B> <k> : "𝕜"
      <Multi_key> <B> <l> : "𝕝"
      <Multi_key> <B> <m> : "𝕞"
      <Multi_key> <B> <n> : "𝕟"
      <Multi_key> <B> <o> : "𝕠"
      <Multi_key> <B> <p> : "𝕡"
      <Multi_key> <B> <q> : "𝕢"
      <Multi_key> <B> <r> : "𝕣"
      <Multi_key> <B> <s> : "𝕤"
      <Multi_key> <B> <t> : "𝕥"
      <Multi_key> <B> <u> : "𝕦"
      <Multi_key> <B> <v> : "𝕧"
      <Multi_key> <B> <w> : "𝕨"
      <Multi_key> <B> <x> : "𝕩"
      <Multi_key> <B> <y> : "𝕪"
      <Multi_key> <B> <z> : "𝕫"
      <Multi_key> <B> <0> : "𝟘"
      <Multi_key> <B> <1> : "𝟙"
      <Multi_key> <B> <2> : "𝟚"
      <Multi_key> <B> <3> : "𝟛"
      <Multi_key> <B> <4> : "𝟜"
      <Multi_key> <B> <5> : "𝟝"
      <Multi_key> <B> <6> : "𝟞"
      <Multi_key> <B> <7> : "𝟟"
      <Multi_key> <B> <8> : "𝟠"
      <Multi_key> <B> <9> : "𝟡"
      <Multi_key> <b> <A> : "𝐀"
      <Multi_key> <b> <B> : "𝐁"
      <Multi_key> <b> <C> : "𝐂"
      <Multi_key> <b> <D> : "𝐃"
      <Multi_key> <b> <E> : "𝐄"
      <Multi_key> <b> <F> : "𝐅"
      <Multi_key> <b> <G> : "𝐆"
      <Multi_key> <b> <H> : "𝐇"
      <Multi_key> <b> <I> : "𝐈"
      <Multi_key> <b> <J> : "𝐉"
      <Multi_key> <b> <K> : "𝐊"
      <Multi_key> <b> <L> : "𝐋"
      <Multi_key> <b> <M> : "𝐌"
      <Multi_key> <b> <N> : "𝐍"
      <Multi_key> <b> <O> : "𝐎"
      <Multi_key> <b> <P> : "𝐏"
      <Multi_key> <b> <Q> : "𝐐"
      <Multi_key> <b> <R> : "𝐑"
      <Multi_key> <b> <S> : "𝐒"
      <Multi_key> <b> <T> : "𝐓"
      <Multi_key> <b> <U> : "𝐔"
      <Multi_key> <b> <V> : "𝐕"
      <Multi_key> <b> <W> : "𝐖"
      <Multi_key> <b> <X> : "𝐗"
      <Multi_key> <b> <Y> : "𝐘"
      <Multi_key> <b> <Z> : "𝐙"
      <Multi_key> <b> <a> : "𝐚"
      <Multi_key> <b> <b> : "𝐛"
      <Multi_key> <b> <c> : "𝐜"
      <Multi_key> <b> <d> : "𝐝"
      <Multi_key> <b> <e> : "𝐞"
      <Multi_key> <b> <f> : "𝐟"
      <Multi_key> <b> <g> : "𝐠"
      <Multi_key> <b> <h> : "𝐡"
      <Multi_key> <b> <i> : "𝐢"
      <Multi_key> <b> <j> : "𝐣"
      <Multi_key> <b> <k> : "𝐤"
      <Multi_key> <b> <l> : "𝐥"
      <Multi_key> <b> <m> : "𝐦"
      <Multi_key> <b> <n> : "𝐧"
      <Multi_key> <b> <o> : "𝐨"
      <Multi_key> <b> <p> : "𝐩"
      <Multi_key> <b> <q> : "𝐪"
      <Multi_key> <b> <r> : "𝐫"
      <Multi_key> <b> <s> : "𝐬"
      <Multi_key> <b> <t> : "𝐭"
      <Multi_key> <b> <u> : "𝐮"
      <Multi_key> <b> <v> : "𝐯"
      <Multi_key> <b> <w> : "𝐰"
      <Multi_key> <b> <x> : "𝐱"
      <Multi_key> <b> <y> : "𝐲"
      <Multi_key> <b> <z> : "𝐳"
      <Multi_key> <b> <0> : "𝟎"
      <Multi_key> <b> <1> : "𝟏"
      <Multi_key> <b> <2> : "𝟐"
      <Multi_key> <b> <3> : "𝟑"
      <Multi_key> <b> <4> : "𝟒"
      <Multi_key> <b> <5> : "𝟓"
      <Multi_key> <b> <6> : "𝟔"
      <Multi_key> <b> <7> : "𝟕"
      <Multi_key> <b> <8> : "𝟖"
      <Multi_key> <b> <9> : "𝟗"
      <Multi_key> <e> <l> : "ℓ"
      <Multi_key> <d> <e> <e> : "∂"
      <Multi_key> <n> <a> <b> : "∇"
      <Multi_key> <y> <o> : "よ"
      <Multi_key> <space> <space> : "␣"
      <Multi_key> <BackSpace> : "⌫"
      <Multi_key> <Up> : "↑"
      <Multi_key> <Down> : "↓"
      <Multi_key> <Left> : "←"
      <Multi_key> <Right> : "→"
      <Multi_key> <parenleft> <Right> : "↪"
      <Multi_key> <minus> <slash> <greater> : "↛"
      <Multi_key> <less> <slash> <minus> : "↚"
      <Multi_key> <2> <Right> : "⇉"
      <Multi_key> <Tab> : "⇥"
      <Multi_key> <Return> : "↵"
      <Multi_key> <f> <l> : "❧"
      <Multi_key> <o> <k> : "✓"
      <Multi_key> <n> <o> <k> : "✗"
      <Multi_key> <1> <period> : "⒈"
      <Multi_key> <2> <period> : "⒉"
      <Multi_key> <3> <period> : "⒊"
      <Multi_key> <4> <period> : "⒋"
      <Multi_key> <5> <period> : "⒌"
      <Multi_key> <6> <period> : "⒍"
      <Multi_key> <7> <period> : "⒎"
      <Multi_key> <8> <period> : "⒏"
      <Multi_key> <9> <period> : "⒐"
      <Multi_key> <1> <0> <period> : "⒑"
      <Multi_key> <f> <l> <l> : "⌊"
      <Multi_key> <f> <l> <r> : "⌋"
      <Multi_key> <c> <e> <l> : "⌈"
      <Multi_key> <c> <e> <r> : "⌉"
      <dead_circumflex> <bracketleft> : "⌜"
      <dead_circumflex> <bracketright> : "⌝"
      <Multi_key> <2> <exclam> : "‼"
      <Multi_key> <2> <question> : "⁇"
      <Multi_key> <z> <w> : "​"
      <Multi_key> <z> <n> <j> : "‌"
      <Multi_key> <z> <w> <j> : "‍"
      <Multi_key> <w> <j> : "⁠"
      <Multi_key> <period> <bar> <period> : "⋮"
      <Multi_key> <plus> <bar> : "†"
      <Multi_key> <plus> <plus> : "‡"
      <Multi_key> <s> <t> : "ﬆ"
      <Multi_key> <f> <t> : "ﬅ"
      <Multi_key> <underscore> <minus> : "₋"
      <Multi_key> <colon> <colon> : "∷"
      <Multi_key> <numbersign> <G> : "𝄞"
      <Multi_key> <numbersign> <F> : "𝄢"
      <Multi_key> <numbersign> <C> : "𝄡"
      <Multi_key> <degree> <C> : "℃"
      <Multi_key> <degree> <F> : "℉"
      <Multi_key> <m> <u> : "無"
      <Multi_key> <o> <m> : "ॐ"
      <Multi_key> <e> <t> : "ꝫ"
      <Multi_key> <E> <T> : "Ꝫ"
      <Multi_key> <s> <h> : "ʃ"
      <Multi_key> <y> <y> : "☯"
      <Multi_key> <O> <O> : "👀"
      <Multi_key> <greater> <less> : "👉👈"
      <Multi_key> <backslash> <slash> : "¯\\_(ツ)_/¯"
      <Multi_key> <s> <2> <h> : "┐('~'; )┌"
      <Multi_key> <l> <e> : "( ͡° ͜ʖ ͡°)"
      <Multi_key> <m> <e> <h> : "ಠ_ಠ"
      <Multi_key> <t> <f> : "(╯°□°）╯︵ ┻━┻"
      <Multi_key> <q> <t> : "(◕‿◕)"
      <Multi_key> <s> <a> <d> : "(｡•́︿•̀｡)"
      <Multi_key> <r> <r> : "https://www.youtube.com/watch?v=dQw4w9WgXcQ" # for emergency use only
    '';

    onChange = ''
      ibus restart || true
    '';
  };
}
