name: CI
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Install flakes-enabled Nix
        uses: cachix/install-nix-action@v14
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/kqchxcar98r8hj447mz0c0fdvdi5xcw1/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: experimental-features = nix-command flakes
      - name: Set up Cachix
        uses: cachix/cachix-action@v10
        with:
          name: ${{ github.actor }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
      - name: Check flake
        run: nix -vL flake check
      - name: Build ISO image
        run: nix -vL build .#iso
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: iso
          name: Live ISO
          files: result/iso/*.iso
