name: CI
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
      - name: Install flakes-enabled Nix
        uses: cachix/install-nix-action@v16
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/d6m5dgxdh3hnjwkvll0sm5mk4bnrf4rk/install
          install_options: --tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve
          extra_nix_config: experimental-features = nix-command flakes
      - name: Set up Cachix
        uses: cachix/cachix-action@v10
        with:
          name: ${{ github.actor }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - name: Check flake
        run: nix -v flake check --extra-experimental-features ca-derivations
      - name: Build ISO
        run: nix -vL build .#iso -o nixos.iso
      - name: Create ISO release
        id: release
        uses: ncfavier/action-gh-release@delete-existing
        with:
          tag_name: iso
          target_commitish: ${{ github.ref }}
          name: ISO image
          delete_on_existing: true
          files: nixos.iso
          fail_on_unmatched_files: true
      - name: "Vultr: list ISOs"
        id: list_isos
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: https://api.vultr.com/v2/iso
          bearerToken: ${{ secrets.VULTR_API_KEY }}
          method: GET
      - name: Set variables
        id: vars
        env:
          assets: ${{ steps.release.outputs.assets }}
          isos: ${{ steps.list_isos.outputs.response }}
          script: |
            def set($name; $value): "::set-output name=\($name)::\($value)";
            set("upload_data"; {url: $assets[0].browser_download_url}),
            ($isos.isos |
            set("do_vultr"; all(.sha512sum != $sha512)),
            set("nixos_id"; map(select(.filename == "nixos.iso").id)[0] // ""))
        run: |
          read -r sha512 _ < <(sha512sum nixos.iso)
          jq -nr --arg sha512 "$sha512" --argjson assets "$assets" --argjson isos "$isos" "$script"
      - name: "Vultr: delete current nixos.iso"
        uses: fjogeleit/http-request-action@v1.8.1
        if: ${{ steps.vars.outputs.do_vultr == 'true' && steps.vars.outputs.nixos_id }}
        with:
          url: https://api.vultr.com/v2/iso/${{ steps.vars.outputs.nixos_id }}
          bearerToken: ${{ secrets.VULTR_API_KEY }}
          method: DELETE
      - name: "Vultr: upload nixos.iso"
        uses: fjogeleit/http-request-action@v1.8.1
        if: ${{ steps.vars.outputs.do_vultr == 'true' }}
        with:
          url: https://api.vultr.com/v2/iso
          bearerToken: ${{ secrets.VULTR_API_KEY }}
          method: POST
          data: ${{ steps.vars.outputs.upload_data }}
