name: CI
on: [push, pull_request]
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Set up Cachix
        uses: cachix/cachix-action@v12
        with:
          name: ${{ github.actor }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community, mic92
          pathsToPush: nixos.iso
      # - name: Check flake
      #   run: nix flake check
      - name: Build ISO
        run: nix -L build .#iso -o nixos.iso
      - name: Create release
        id: release
        uses: ncfavier/action-gh-release@delete-existing
        with:
          tag_name: iso
          target_commitish: ${{ github.ref }}
          name: ISO image
          delete_on_existing: true
          files: nixos.iso
          fail_on_unmatched_files: true
