name: CI
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
      - name: Install Nix
        uses: cachix/install-nix-action@v16
      - name: Set up Cachix
        uses: ncfavier/cachix-action@cachix-args
        with:
          name: ${{ github.actor }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community, mic92
          pathsToPush: nixos.iso
      # disabled for now because of https://github.com/cachix/cachix-action/issues/89
      # - name: Check flake
      #   run: nix -v flake check
      - name: Build ISO
        run: nix -vL build .#iso -o nixos.iso
      - name: Create release
        id: release
        uses: ncfavier/action-gh-release@delete-existing
        with:
          tag_name: iso
          target_commitish: ${{ github.ref }}
          name: ISO image
          delete_on_existing: true
          files: nixos.iso
          fail_on_unmatched_files: true