name: CI
on: [push, pull_request]
jobs:
  check:
    name: Flake check
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v5
        with:
          nix_version: 2.4pre20201205_a5d85d0
          nix_conf: experimental-features = nix-command flakes
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Flake check
        run: nix -vL flake check
  iso:
    name: Build ISO
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v5
        with:
          nix_version: 2.4pre20201205_a5d85d0
          nix_conf: experimental-features = nix-command flakes
      - name: Set up Cachix
        uses: cachix/cachix-action@v10
        with:
          name: ncfavier
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build ISO
        run: nix -vL build -o iso .#packages.x86_64-linux.iso
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ISO
          path: iso/iso/*.iso
          if-no-files-found: error
