name: CI
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Set up Cachix
        uses: cachix/cachix-action@v16
        with:
          name: ${{ github.actor }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community, mic92
          pathsToPush: iso
      # - name: Check flake
      #   run: nix flake check
      - name: Build ISO
        run: nix -L build .#iso -o iso
      - name: Create release
        run: |
          gh release upload iso iso/iso/nixos*.iso --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
